### ISSUE TITLE
Win 10 tweaker

### ISSUE THREAD

**Issue by deyzaneck** [denis-g/windows10-latency-optimization#2]
В интернете постоянно пишут что в новых версиях этой программы есть вирус.

**Comment by denis-g** [comment]
Всё уже пережёвано кучу раз. [Во-первых](https://win10tweaker.ru/forum/topic/%D0%BA%D0%BB%D0%B5%D0%B2%D0%B5%D1%82%D0%B0-%D0%B2-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE-%D0%BF%D1%80%D0%BE-win10tweaker), это было исполнение удалённого кода и то что это потенциальный бэкдор никто не отрицает, на текущий момент выпилено из приложения. Во-вторых, не надо качать всякие ломанные версии (последняя ломаная 16, а сейчас уже 18).

В остальном же, здесь никто не запрещает использовать любой другой твикер (если он действительно нужен) или же вообще обойтись без него. Лично у меня с win10tweaker не было проблем и он делает то, что мне нужно.
