### ISSUE TITLE
I saw this to reduce the audio delay in windows 10, is this really useful?

### ISSUE THREAD

**Issue by 0ne0ay** [denis-g/windows10-latency-optimization#3]
https://github.com/miniant-git/REAL
My English is not good, sorry

**Comment by denis-g** [comment]
Hi, this is fix sound driver latency, but this is not working on my system - audio latency is always 10ms. Maybe util not working on the latest Win10 or with my sound driver, or problem is not pronounced (probably).
Also, I haven't found tests with this utility on the Internet, so I can't say anything about it.
In most cases, it is enough to [disable "Exclusive Mode"](https://i1.wp.com/neosmart.net/wiki/wp-content/uploads/sites/5/2017/03/Advanced-Settings.png?ssl=1) and probably this is a problem with another device/driver/system.

**Comment by 0ne0ay** [comment]
> 嗨，这是修复声音驱动程序延迟，但这在我的系统上不起作用 - 音频延迟始终为 10 毫秒。也许 util 不适用于最新的 Win10 或我的声音驱动程序，或者问题不明显（可能）。
> 另外，我还没有在 Internet 上找到有关此实用程序的测试，因此我无法对此发表任何评论。
> 在大多数情况下，[禁用“独占模式”](https://i1.wp.com/neosmart.net/wiki/wp-content/uploads/sites/5/2017/03/Advanced-Settings.png?ssl=1)就足够了，这可能是另一个设备/驱动程序/系统的问题。

Ok thank you very much
