### ISSUE TITLE
Добавление разделов MSI Autoburner и BIOS

### ISSUE THREAD

**Issue by Top0wl** [denis-g/windows10-latency-optimization#4]
Добрый день, мне очень понравилась ваша статья, очень хорошо всё описано, но я думаю в ней для полного счастья не хватает 2 раздела настройки, а после тестов, а именно разгон или же увеличение потребления в MSI AB, а также настройка самого BIOS, можно в принципе и буст памяти затронуть, а так же тесты после этих настроек. Благодарю за статью, сохранил себе её, буду пользоваться!

**Comment by denis-g** [comment]
Привет, по поводу MSA и биос я не зря делал сноски - очень много нюансов как от железа, так и параметров. Если кому-то хочется в это углубляться, то это уже самостоятельно - материалов на эту тему куча. В дополнение могу порекомендовать канал [FR33THY](https://www.youtube.com/c/FR33THY) (на англ.)
Сам же пришёл к тому, что в большинстве случаев это порождает только проблемы на лично моём железе и биосе, что в итоге ограничился только XMP и некоторыми твиками в MSA.
