### ISSUE TITLE
Нету некоторых пунктов реестра

### ISSUE THREAD

**Issue by mgarst** [denis-g/windows10-latency-optimization#6]
Здравствуйте denis-g! Прочитал вашу статью по оптимизации Windows 10 и столкнулся с тем, что у меня в реестре нет некоторых пунктов, которые у вас есть в статье. Если их нет, то мне нужно будет их создать?

**Comment by denis-g** [comment]
@mgarst смотря какие параметры вы имеете в виду.
К тому же везде указаны какие в оригинальной Windows параметры по сравнению с измененями (хоть и не с последней версии, но они не должны меняться). Если их нет, то надо создать.
