### ISSUE TITLE
Большое количество USB расшириных хостов

### ISSUE THREAD

**Issue by iMrGreenBoy** [denis-g/windows10-latency-optimization#8]
Здравствуйте. Столкнулся с такой проблемой у меня много расширенных USB хостов в msinfo32.exe. Не понимаю как определить какой мне нужн. Подскажите пожалуйста как определить.
![msinfo32_GdR4UcNsA7](https://github.com/denis-g/windows10-latency-optimization/assets/116056198/0a243ffe-6c69-480c-91bb-f52ec2664d67)

**Comment by denis-g** [comment]
@iMrGreenBoy видимо какая-то специфика конкретно вашего железа/драйверов.
Посмотрите в диспетчере через группировку по соединениям, как [тут](https://www.intel.com/content/www/us/en/support/articles/000005622/software/chipset-software.html)

![](https://www.intel.com/content/dam/support/us/en/images/chipsets/usb3/sb/img/cs033074_devicesbyconnectionfix.jpg)

![](https://github.com/denis-g/windows10-latency-optimization/assets/771963/928bcf8e-f0ea-49ed-92eb-c935b93f2f3f)

Т.е. по конкретным устройствам (видео, клава/мышь и тп) выбрать нужные хосты к которым они подключены и уже смотреть какой у этого хоста IRQ во вкладке "Ресурсы"

![](https://forums.flightsimulator.com/uploads/default/original/3X/b/1/b1e9d3a5edf4fc6275194d04b3011cecc8159efe.png)

Ну а дальше найти его в msinfo32.

**Comment by iMrGreenBoy** [comment]
@denis-g Спасибо большое. Буду пробовать.

**Comment by iMrGreenBoy** [comment]
@denis-g 
![mmc_CwUWHX4TU5](https://github.com/denis-g/windows10-latency-optimization/assets/116056198/8f12edb3-76c5-43a3-873b-f6f52eb8e80d)
![mmc_onUJ7WdcYu](https://github.com/denis-g/windows10-latency-optimization/assets/116056198/1f246903-34ed-44ba-a6c0-551920268ba9)
![mmc_y02GImX2p6](https://github.com/denis-g/windows10-latency-optimization/assets/116056198/3832d030-e8f3-4349-98f2-8c981d85c385)
![mmc_ync0ALZM3C](https://github.com/denis-g/windows10-latency-optimization/assets/116056198/28bd5c21-40dd-48da-aa8d-bdc7957999b2)

Здравствуйте. Я сделал как вы и подсказали. И обноружил там такую картину. Их и в ресурсах много. Попробую прописать первый из них. Поскольку даже не могу представить как их всех прописать. Я так понял это особенность AMD процессоров и материнок для них.

**Comment by denis-g** [comment]
> Я так понял это особенность AMD процессоров и материнок для них.

Во-первых, да.

> Настройки и твики описанные здесь основаны на системе с CPU Intel и GPU от nVidia

Это во-вторых. Как раз из-за того, что у АМД много своих приколюх и что-то делается кардинально иначе чем здесь описано.
